"""Per-engine "not supported yet" gates for the shared parity suite.

A parity test is tagged with ``@pytest.mark.feature("<id>")``. If that id is in an
engine's gate set, the test is ``xfail`` for that engine (it may fail without
turning CI red). When an engine implements the behavior, **delete the id from its
set in the same change** — the matching parity tests then become required-to-pass.

This is the TDD ratchet: the Python set starts large (the engine is empty) and
drains to zero as the engine lands; deleting an entry is how a feature gets
"promoted" from optional to required. Each entry that the Python set still holds
but the Polars set does not is a polars gap the Python engine is expected to fix.
"""

from __future__ import annotations

# Polars engine — documented in docs/known_gaps.md. Type coercion is decided at
# expression-build time without a schema, so these cross-type cases raise instead
# of coercing the way Spark does.
POLARS_NOT_SUPPORTED = {
    "arithmetic.numeric_plus_string",
    "arithmetic.int_plus_date",
}

# Python engine — gated behaviors awaiting the build → analyze → evaluate engine
# (#102). Drain an id as each behavior lands; entries the Python set holds but the
# Polars set does not are polars gaps the Python engine is expected to fix.
PYTHON_NOT_IMPLEMENTED = {
    "arithmetic.int_plus_date",
    # column_parity_test.py — Column arithmetic / comparison / cast (lifted from column_test.py).
    "column.arithmetic.col_col",
    "column.comparison.col_col",
    "column.arithmetic.with_nulls",
    "column.arithmetic.literal_col",
    "column.arithmetic.col_col_mixed_types",
    "column.comparison.col_col_mixed_types",
    "column.cast.string_to_numeric_valid",
    "column.try_cast.string_to_numeric_invalid_null",
    "column.cast.string_to_numeric_invalid_raises",
    "column.cast.string_to_boolean_invalid_raises",
    "column.cast.int_to_boolean",
    "column.cast.double_to_boolean",
    "column.try_cast.string_to_boolean",
    "column.cast.string_to_boolean_valid",
    "column.cast.int_to_other",
    "column.try_cast.inside_when_then",
    # dataframe_parity_test.py — DataFrame ops (lifted from dataframe_test.py).
    "dataframe.select.by_list_str",
    "dataframe.select.by_list_columns",
    "dataframe.select.by_column_name",
    "dataframe.select.by_pointer_list",
    "dataframe.select.by_expression",
    "dataframe.select.all_columns_with_aliases",
    "dataframe.select.literal_only_broadcasts",
    "dataframe.select.literal_broadcast_empty",
    "dataframe.with_column.null_lit_empty_rows",
    "dataframe.with_column.add",
    "dataframe.with_column.replace",
    "dataframe.with_columns.add_multiple",
    "dataframe.with_columns.replace_existing",
    "dataframe.with_columns.mix_add_and_replace",
    "dataframe.with_columns.single_entry",
    "dataframe.with_columns.references_prior_column",
    "dataframe.with_column.renamed",
    "dataframe.drop.columns",
    "dataframe.drop.unpack_list",
    "dataframe.drop.column_expr",
    "dataframe.drop.missing_column_ignored",
    "dataframe.is_not_null",
    "dataframe.reverse_arithmetic_operators",
    "dataframe.logical_operations",
    "dataframe.filter_and_where",
    "dataframe.rlike",
    "dataframe.isin",
    "dataframe.groupby.aggregations",
    "dataframe.groupby.collect_list",
    "dataframe.groupby.collect_set",
    "dataframe.groupby.collect_list_nested_aliased_struct",
    "dataframe.join.polars_joins",
    "dataframe.join.non_spark_duplicated_keys",
    "dataframe.join.with_duplicated_spark_keys",
    "dataframe.fillna.pyspark_fillna",
    "dataframe.fillna.fillna",
    "dataframe.getitem.column",
    "dataframe.getitem.list",
    "dataframe.order_by.comparison",
    "dataframe.order_by.int",
    "dataframe.union_by_name.basic",
    "dataframe.union_by_name.allow_missing",
    # functions_parity_test.py — pyspark.sql.functions parity (lifted from functions_test.py).
    "functions.abs.expression",
    "functions.abs.float",
    "functions.abs.integer",
    "functions.abs.of_subtraction_withcolumn",
    "functions.abs.parametrized",
    "functions.array.basic",
    "functions.array_contains_and_size",
    "functions.array_filter_and_transform",
    "functions.asc",
    "functions.coalesce",
    "functions.concat.accepts_string_name_or_column",
    "functions.concat.coerces_integers",
    "functions.concat.single_column_identity",
    "functions.concat.two_parts_any_null_yields_null",
    "functions.count.column",
    "functions.count.star",
    "functions.count.star_no_groupby",
    "functions.create_map.basic",
    "functions.create_map.getitem_lookup",
    "functions.date_format.basic",
    "functions.date_format.time_parts",
    "functions.date_sub_and_datediff",
    "functions.datediff.iso8601_string",
    "functions.datetime_ge_date_sub",
    "functions.desc",
    "functions.element_at.array_oob_raises",
    "functions.element_at.array_valid",
    "functions.element_at.array_zero_raises",
    "functions.element_at.lit_int_index",
    "functions.element_at.map_literal_string_key",
    "functions.element_at.map_missing_literal_key_returns_null",
    "functions.explode",
    "functions.filter.by_struct_field_equality",
    "functions.filter.getitem_int_in_filter",
    "functions.filter.getitem_string_key_on_map_in_filter",
    "functions.first_agg",
    "functions.floor",
    "functions.from_json.struct",
    "functions.get_json_object",
    "functions.greatest.basic",
    "functions.initcap",
    "functions.isnan",
    "functions.least.all_nulls",
    "functions.least.basic",
    "functions.length.str_vs_column",
    "functions.lower.str_vs_column",
    "functions.map_from_entries.getitem_lookup",
    "functions.map_from_entries.long_value",
    "functions.map_keys",
    "functions.md5.binary",
    "functions.md5.string",
    "functions.monotonically_increasing_id",
    "functions.months_between",
    "functions.nullif.basic",
    "functions.nullif.preserves_e1",
    "functions.pow.col_col",
    "functions.pow.literal_exponent",
    "functions.regexp_replace.str_vs_column",
    "functions.sort_array.asc",
    "functions.sort_array.desc",
    "functions.split",
    "functions.struct.aliased_columns",
    "functions.struct.aliased_literals",
    "functions.struct.mixed_aliased_lit_and_plain_col",
    "functions.struct.nested_aliased_inner",
    "functions.struct.oracle",
    "functions.substring",
    "functions.to_date.malformed_raises",
    "functions.to_date.with_format",
    "functions.to_json.array",
    "functions.to_json.struct",
    "functions.to_json.struct_aliased_literals",
    "functions.to_timestamp.iso_t_separator_raises",
    "functions.to_timestamp.no_format",
    "functions.to_timestamp.no_format_iso8601_z",
    "functions.to_timestamp.no_format_malformed_raises",
    "functions.to_timestamp.with_format",
    "functions.to_timestamp.with_format_malformed_raises",
    "functions.transform.getitem_struct_inside",
    "functions.transform.struct_and_explode",
    "functions.transform.struct_in_when_otherwise",
    "functions.trim",
    "functions.try_divide",
    "functions.try_element_at.accepts_column",
    "functions.try_element_at.array_last_element",
    "functions.try_element_at.array_negative_index",
    "functions.try_element_at.array_oob_returns_null",
    "functions.try_element_at.array_positive_index",
    "functions.try_element_at.lit_int_index",
    "functions.try_element_at.map_literal_key_via_lit",
    "functions.try_element_at.map_string_extraction_is_column_name",
    "functions.try_to_date.column_input",
    "functions.try_to_date.custom_format",
    "functions.try_to_date.custom_format_malformed",
    "functions.try_to_date.default_format_malformed",
    "functions.try_to_date.valid_matches_to_date",
    "functions.try_to_timestamp.column_input",
    "functions.try_to_timestamp.default_malformed_returns_null",
    "functions.try_to_timestamp.iso_t_separator_returns_null",
    "functions.try_to_timestamp.valid",
    "functions.try_to_timestamp.with_format_malformed_returns_null",
    "functions.when.basic",
    "functions.when.chained_boolean_output",
    "functions.when.lit_none_preserves_double",
    "functions.when.lit_none_preserves_integer",
    "functions.when.lit_none_preserves_string",
}

GATES = {
    "polars": POLARS_NOT_SUPPORTED,
    "python": PYTHON_NOT_IMPLEMENTED,
}

# Ratchet: the Python gate may only shrink. This is a committed high-water mark —
# lower it (never raise it) when you delete entries. The ratchet test enforces
# that the live set never exceeds this number, so a regression can't quietly
# re-gate a behavior instead of being fixed.
PYTHON_GATE_HIGH_WATER_MARK = 165
