# Release a new version of SparkleFrame. Changes that take place:
# -
# - Documentation is regenerated and a new version added to the docs.

name: 'Deploy Docs'

on:

  # Allow for manual invocation
  workflow_dispatch:

jobs:
#  predeploy:
#    uses: ./.github/workflows/predeploy.yml

  deploy-docs:
#    needs: predeploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Dependencies
        uses: './.github/actions/setup-dependencies'
      - name: Download version file
        uses: actions/download-artifact@v4
        with:
          name: version.txt
          path: sparkleframe
      - name: Store version number
        run: echo "VERSION_NUMBER=$(cat sparkleframe/version.txt)" >> $GITHUB_ENV
      - name: Create new branch
        run: |
          git config --global user.email "flypipe@dummy.com"
          git config --global user.name "flypipe"
          echo "make docs-deploy version=${{ env.VERSION_NUMBER }}"
